### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chaoyin0102**
陳昭穎

http://13.230.214.9:3000/api/attractions?page=1
http://13.230.214.9:3000/api/attractions?page=0&keyword=藝文館所
http://13.230.214.9:3000/api/attractions?page=0&keyword=北
http://13.230.214.9:3000/api/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review explicitly from the right side in this page, so that I can review for you.

**Comment by chaoyin0102** [comment]
> You should request review explicitly from the right side in this page, so that I can review for you.

Added the reviewer, thanks a lot!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response of http://13.230.214.9:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80 exceeds max 12 data in 1 page.
2. Use `LIMIT` in SQL query to do range selection, rather than get all data and do it in your own code.
3. Use second parameters of execute method to combine variables into SQL query.

Solve issues and re-request review.

**Comment by chaoyin0102** [comment]
> 1. Response of http://13.230.214.9:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80 exceeds max 12 data in 1 page.
> 2. Use `LIMIT` in SQL query to do range selection, rather than get all data and do it in your own code.
> 3. Use second parameters of execute method to combine variables into SQL query.
> 
> Solve issues and re-request review.

Had added LIMIT into sql, kindly check again.
Many thanks!

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by chaoyin0102** [comment]
> Re-request review from reviewers section in the right side of this page, so that I can review for you.

Done! Thanks for the notice.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Use second parameters of execute method to combine variables into SQL query.

It's very important to prevent SQL Injection, as we discussed weeks ago.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
